name: Cache Analyzer Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show hardware
        run: |
          echo "=== L1 Data Cache ==="
              getconf -a | grep -i LEVEL1_DCACHE

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run cache analyzer
        run: |
          for i in {1..36}; do
            echo
            echo "========== Run $i =========="
            ./build/cache_analyzer
          done
